apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: e-commerce
type: Opaque
stringData:
  express_session_secret: fhbvdhfhasjhdggjhkiwegs
  mongo_uri: mongodb+srv://e-commerce:EYNgsxkulYAfVCCK@cluster0.tx6by.mongodb.net